<a href="https://colab.research.google.com/github/lukk1ane/DataScience2025/blob/giorgi_kezevadze/DS_Numpy_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1

In [5]:
import numpy as np

arr = np.arange(1,11,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Task 2

In [7]:
arr = np.arange(0,20,1)
extracted = arr[3:9]
print(extracted)

[3 4 5 6 7 8]


Task 3

In [11]:
arr = np.arange(0,25,1).reshape(5,5)
extracted = arr[0:2,-2:]
print(arr,extracted)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] [[3 4]
 [8 9]]


Task 4

In [13]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,4,6,8])
sum = np.add(arr1,arr2)
product = np.multiply(arr1,arr2)
sine = np.sin(arr2)
print(sum,product,sine)

[ 3  6  9 12] [ 2  8 18 32] [ 0.90929743 -0.7568025  -0.2794155   0.98935825]


Task 5

In [20]:
arr = np.random.randint(50,size = 20)
extracted = arr[arr > 25]
print(arr)
print(extracted)

[29  0 32 45 41  8 41 17 48  3 17 47 39  1 10 40 25 17 42 20]
[29 32 45 41 41 48 47 39 40 42]


Task 6

In [29]:
arr = np.arange(25).reshape(5,5)
print(arr)
arr[np.arange(5),np.arange(5)] = 0
rows, cols = np.indices(arr.shape)
print(np.indices(arr.shape))
arr[rows != cols] *= 2
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[[0 0 0 0 0]
  [1 1 1 1 1]
  [2 2 2 2 2]
  [3 3 3 3 3]
  [4 4 4 4 4]]

 [[0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]
  [0 1 2 3 4]]]
[[ 0  2  4  6  8]
 [10  0 14 16 18]
 [20 22  0 26 28]
 [30 32 34  0 38]
 [40 42 44 46  0]]


Task 7

In [36]:
arr = np.arange(1,10).reshape(3,3)
extracted = arr[1,:-1]
print(arr)
print(extracted)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5]


Task 8

In [38]:
arr = np.random.rand(2,3)
transposed = np.transpose(arr)
print(arr)
print(transposed)

[[0.15913622 0.32497186 0.61160196]
 [0.80391918 0.21303487 0.07100333]]
[[0.15913622 0.80391918]
 [0.32497186 0.21303487]
 [0.61160196 0.07100333]]


Task 9

In [39]:
arr1 = np.arange(0,9).reshape(3,3)
arr2 = np.arange(0,3)
sum = np.add(arr1,arr2)
print(arr1)
print(arr2)
print(sum)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


Task 10

In [40]:
arr = np.arange(0,16).reshape(4,4)
rows = np.array([0, 2, 3])
cols = np.array([1, 3, 2])

elements = arr[rows, cols]
print(arr)
print(elements)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 1 11 14]
