In [6]:
# Section 1

import numpy as np
np.random.seed(42)
scores = np.random.randint(50, 100, size=(6,5))

# task 1

# 1.1
modified_scores = scores.copy()

# 1.2
modified_scores[[0, 1, 2, 3, 4], [0,1,2,3,4]] = 100
print(modified_scores)
# 1.3
modified_scores[modified_scores < 60] = modified_scores[modified_scores < 60] * 1.2
print(modified_scores)
# 1.4
modified_scores[modified_scores> 100] = 100
print(scores, modified_scores)



[[100  78  64  92  57]
 [ 70 100  68  72  60]
 [ 60  73 100  89  73]
 [ 52  71  51 100  93]
 [ 79  87  51  70 100]
 [ 61  71  93  74  98]]
[[100  78  64  92  68]
 [ 70 100  68  72  60]
 [ 60  73 100  89  73]
 [ 62  71  61 100  93]
 [ 79  87  61  70 100]
 [ 61  71  93  74  98]]
[[88 78 64 92 57]
 [70 88 68 72 60]
 [60 73 85 89 73]
 [52 71 51 73 93]
 [79 87 51 70 82]
 [61 71 93 74 98]] [[100  78  64  92  68]
 [ 70 100  68  72  60]
 [ 60  73 100  89  73]
 [ 62  71  61 100  93]
 [ 79  87  61  70 100]
 [ 61  71  93  74  98]]


In [7]:
# Task 2.1
print(modified_scores.mean(axis=1))
print(modified_scores.std(axis=1))
print(modified_scores.min(axis=1))
print(modified_scores.max(axis=1))
# Task 2.2
print(modified_scores.mean(axis=0))
print(np.median(modified_scores, axis=0))
above_80 = np.sum(modified_scores > 80, axis=0)
print(above_80)

[80.4 74.  79.  77.4 79.4 79.4]
[13.76372043 13.62350909 13.95707706 16.13195586 13.48480626 13.92264343]
[64 60 60 61 61 61]
[100 100 100 100 100  98]
[72.         80.         74.5        82.83333333 82.        ]
[66.  75.5 66.  81.5 83. ]
[1 2 2 3 3]


In [ ]:
import numpy as np
# Task 3
# 3.1
student_averages = np.mean(modified_scores, axis=1)
boolean_mask = student_averages >= 75
print(boolean_mask)

# 3.2

excellent_mask = modified_scores >= 85
num_excellent = np.sum(excellent_mask)

avg_mask = np.mean(modified_scores, axis=0)

print(np.argmax(avg_mask)
)

bad_mask = modified_scores < 60
students_below_60 = np.where(np.any(bad_mask, axis=1))[0]
print(students_below_60)


[ True False  True  True  True  True]
3
[]
[]


In [16]:
print("="*60)
print("             1. NUMPY SOLUTIONS")
print("="*60)

## 1.1 Matrix Manipulations (Vectorized)
print("--- 1.1 Matrix Manipulations ---")

# 1. Create a copy of the scores matrix
modified_scores = scores.copy()

# 2. Set all diagonal elements to 100
# np.diag_indices(N) returns row and column indices for a diagonal of an NxN array
N = modified_scores.shape[0] # Get the number of rows/students (6)
# We use min(6, 5) to handle non-square matrices, but since N=6 and M=5, we use 5
diag_indices = np.arange(min(modified_scores.shape))
modified_scores[diag_indices, diag_indices] = 100

# 3. For all scores below 60, multiply by 1.2 (Grade Curve Adjustment)
# Create a boolean mask where scores < 60
mask_curve = (modified_scores < 60)
# Apply the multiplication ONLY where the mask is True (vectorized operation)
modified_scores[mask_curve] = modified_scores[mask_curve] * 1.2

# 4. Clip all values to a maximum of 100
# np.clip is the standard vectorized way to cap values
modified_scores = np.clip(modified_scores, a_min=None, a_max=100)

# 5. Print both original and modified matrices
print(f"Original Scores Matrix:\n{scores}")
print(f"\nModified Scores Matrix:\n{modified_scores}")

print("\n" + "-"*30)

## 1.2 Statistical Analysis (Vectorized)
print("--- 1.2 Statistical Analysis ---")

# Calculate and print for each student (row-wise, axis=1)
print("\n[Student Performance (Row-wise)]")
print(f"Average Score (Row Means):\n{np.mean(modified_scores, axis=1).round(2)}")
print(f"Standard Deviation (Row Std):\n{np.std(modified_scores, axis=1).round(2)}")
print(f"Minimum Score (Row Min):\n{np.min(modified_scores, axis=1)}")
print(f"Maximum Score (Row Max):\n{np.max(modified_scores, axis=1)}")

# Calculate and print for each subject (column-wise, axis=0)
print("\n[Subject Performance (Column-wise)]")
print(f"Mean Score (Col Means):\n{np.mean(modified_scores, axis=0).round(2)}")
print(f"Median Score (Col Medians):\n{np.median(modified_scores, axis=0)}")

# Number of students scoring above 80 (Boolean summation is key here)
scores_above_80 = (modified_scores > 80)
# Summing a boolean array along axis=0 (columns) counts the True values per column
num_above_80 = np.sum(scores_above_80, axis=0)
print(f"Number of Students Scoring > 80 per Subject:\n{num_above_80}")

print("\n" + "-"*30)

## 1.3 Performance Classification (Vectorized)
print("--- 1.3 Performance Classification ---")

# 1. Create a boolean mask for students with average >= 75
student_averages = np.mean(modified_scores, axis=1)
mask_high_achievers = (student_averages >= 75)
print(f"Boolean Mask for Students with Average >= 75:\n{mask_high_achievers}")

# 2. Calculate the percentage of excellent scores (>= 85) in the matrix
mask_excellent = (modified_scores >= 85)
# Count the total number of True values
num_excellent = np.sum(mask_excellent)
# Total number of elements
total_elements = modified_scores.size
percentage_excellent = (num_excellent / total_elements) * 100
print(f"Percentage of Excellent Scores (>= 85): {percentage_excellent:.2f}%")

# 3. Find the subject (column index) with the highest average
subject_averages = np.mean(modified_scores, axis=0)
highest_avg_index = np.argmax(subject_averages)
print(f"Subject with the Highest Average Score (Index): {highest_avg_index}")

# 4. Identify students (row indices) who scored below 60 in *any* subject
# Check if *any* score in a row (axis=1) is less than 60
mask_needs_help = np.any(modified_scores < 60, axis=1)
# np.where returns the indices where the condition is True
students_needing_help = np.where(mask_needs_help)[0]
print(f"Row Indices of Students Who Scored Below 60 in ANY Subject: {students_needing_help}")


             1. NUMPY SOLUTIONS
--- 1.1 Matrix Manipulations ---
Original Scores Matrix:
[[88 78 64 92 57]
 [70 88 68 72 60]
 [60 73 85 89 73]
 [52 71 51 73 93]
 [79 87 51 70 82]
 [61 71 93 74 98]]

Modified Scores Matrix:
[[100  78  64  92  68]
 [ 70 100  68  72  60]
 [ 60  73 100  89  73]
 [ 62  71  61 100  93]
 [ 79  87  61  70 100]
 [ 61  71  93  74  98]]

------------------------------
--- 1.2 Statistical Analysis ---

[Student Performance (Row-wise)]
Average Score (Row Means):
[80.4 74.  79.  77.4 79.4 79.4]
Standard Deviation (Row Std):
[13.76 13.62 13.96 16.13 13.48 13.92]
Minimum Score (Row Min):
[64 60 60 61 61 61]
Maximum Score (Row Max):
[100 100 100 100 100  98]

[Subject Performance (Column-wise)]
Mean Score (Col Means):
[72.   80.   74.5  82.83 82.  ]
Median Score (Col Medians):
[66.  75.5 66.  81.5 83. ]
Number of Students Scoring > 80 per Subject:
[1 2 2 3 3]

------------------------------
--- 1.3 Performance Classification ---
Boolean Mask for Students with Average >