In [20]:
"""
1. Array Creation and Basic Operations
 Task: Create a 1D NumPy array containing numbers from 1 to 10. Then, calculate the sum and
product of all elements in the array.
"""
import numpy as np

arr = np.arange(1, 11)
print(np.sum(arr))
print(np.prod(arr))

55
3628800


In [21]:
"""
2. Array Indexing and Slicing
 Task: Create a 1D array with numbers from 0 to 20. Extract the elements from index 3 to 8.
"""

arr = np.arange(21)
print(arr[3:9])

[3 4 5 6 7 8]


In [22]:
""" 
3. 2D Array Manipulation
 Task: Create a 5x5 array with values from 0 to 24. Extract the first two rows and the last two
columns.
"""

arr = np.arange(25).reshape(5, 5)
print(arr[:2, -2:])

[[3 4]
 [8 9]]


In [23]:
""" 
4. Element-wise Mathematical Operations
 Task: Create two arrays: a = [1, 2, 3, 4] and b = [2, 4, 6, 8]. Perform element-wise addition,
multiplication, and calculate the sine of each element in b.
"""

a = np.array([1, 2, 3, 4])
b = np.array([2, 4, 6, 8])
print(a + b)
print(a * b)
print(np.sin(b))

[ 3  6  9 12]
[ 2  8 18 32]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825]


In [24]:
""" 
idexing and Boolean Masking
 Task: Create a 1D array with random integers between 0 and 50 (size 20). Extract elements that
are greater than 25 and less than 40 using boolean masking.
"""

arr = np.random.randint(0, 50, size=20)
mask = (arr > 25) & (arr < 40)
print(arr[mask])

[28 29 35 39 30 37]


In [25]:
""" 6. Multi-dimensional Array Challenge
 Task: Create a 5x5 matrix using np.arange(25).reshape(5, 5). Set the diagonal elements to zero
and multiply all other elements by 2.
"""

matrix = np.arange(25).reshape(5, 5)
np.fill_diagonal(matrix, 0)
matrix[matrix != 0] *= 2
print(matrix)

[[ 0  2  4  6  8]
 [10  0 14 16 18]
 [20 22  0 26 28]
 [30 32 34  0 38]
 [40 42 44 46  0]]


In [26]:
""" Array Slicing
 Task: Create a 3x3 NumPy array with values from 1 to 9. Extract the second row and all columns except the last one
"""

arr = np.arange(1, 10).reshape(3, 3)
print(arr[1, :-1])

[4 5]


In [27]:
""" 
8. Transposing an Array
 Task: Create a 2x3 array and transpose it.
"""

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
""" 9. Broadcasting
 Task: Create a 3x3 array and a 1x3 array. Use broadcasting to add the 1x3 array to each row of
the 3x3 array.
"""

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([10, 20, 30])
result = arr + b
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
""" 10. Fancy Indexing with 2D arrays
 Task: Create a 4x4 array and use fancy indexing to extract the elements at positions (0, 1), (2, 3),
and (3, 2).
"""

arr = np.arange(16).reshape(4, 4)
rows = np.array([0, 2, 3])
cols = np.array([1, 3, 2])
print(arr[rows, cols])