In [ ]:
import numpy as np
a = np.arange(25).reshape(5, 5)

print(a[:, 1::2])
print(a[1::2, :3:2])
print(a[-1, ::])




[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]
 [21 23]]
[[ 5  7]
 [15 17]]
[20 21 22 23 24]


In [15]:
a = np.array([10, 20, 30, 40, 50])
mask = np.array([0, 1, 0, 1, 0], dtype = bool)
y = a[mask]
print(y)
mask2 = a > 25
y2 = a[mask2]
print(y2)

[20 40]
[30 40 50]


In [28]:
a = np.arange(25).reshape(5, 5)
mask = a % 3 == 0
print(a)
print(a[[0, 1, 2, 3], [1, 2, 3, 4]])
print(np.argmax(a))
print(np.unravel_index(np.argmax(a), a.shape))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  7 13 19]
24
(np.int64(4), np.int64(4))


In [42]:
arr = np.arange(-15, 15).reshape(5, 6) ** 2
print(arr.max(axis=1))
print(arr.mean(axis=0, dtype = np.int32))
print(np.unravel_index(arr.argmin(), arr.shape), arr.argmin())



[225  81   9  64 196]
[81 76 73 72 73 76]
(np.int64(2), np.int64(3)) 15
