In [1]:
import numpy as np

In [ ]:
# Task 1

arr1 = np.arange(1, 10)
print(arr1)
print(np.sum(arr1))
print(np.prod(arr1))

[1 2 3 4 5 6 7 8 9]
45
362880


In [9]:
# Task 2

arr2 = np.arange(0, 20)
print(arr2[3:8])

[3 4 5 6 7]


In [17]:
# Task 3
arr2 = np.arange(0, 25)
arr2 = arr2.reshape(5,5)
print(arr2)
print(arr2[0:2, :])
print(arr2[:, -2:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [ ]:
# Task 4
a = np.array([1,2,3,4])
b = np.array([2,4,6,8])
print(a + b)
print(a * b)
print(np.sin(b))

[ 3  6  9 12]
[ 2  8 18 32]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825]


In [ ]:
# Task 5
from random import randint

arr = np.array([randint(1, 50) for i in range(0, 20)])
arr = np.random.randint(1, 51, size=20)
mask = (arr > 25) & (arr < 40)

arr2 = arr[mask]
print(arr2)

[35 38 30 29]


In [33]:
# Task 6

array = np.arange(25).reshape(5, 5)
np.fill_diagonal(array, 0)
array = np.where(array != 0, array * 2, 0)
print(array)


[[ 0  2  4  6  8]
 [10  0 14 16 18]
 [20 22  0 26 28]
 [30 32 34  0 38]
 [40 42 44 46  0]]


In [40]:
# Task 7
array = np.arange(9).reshape(3,3)
print(array[2, :])
print(array[:, :2])

[6 7 8]
[[0 1]
 [3 4]
 [6 7]]


In [44]:
# Task 8
array = np.arange(1, 7).reshape(2,3)
print(array, "\n",np.transpose(array))

[[1 2 3]
 [4 5 6]] 
 [[1 4]
 [2 5]
 [3 6]]


In [46]:
# Task 9
array1 = np.arange(1, 10).reshape(3,3)
array2 = np.arange(1, 4).reshape(1,3)
print(array1, array2, array2+array1)


[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]] [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [49]:
# Task 10
array = np.arange(1, 17).reshape(4, 4)
print(array[[0, 2, 3], [2, 3, 2]], array)

[ 3 12 15] [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
